# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

# 1) Declare your build‑time args
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_KEY
ARG GEMINI_API_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXT_PUBLIC_PHONEPE_CLIENT_ID
ARG NEXT_PUBLIC_PHONEPE_MERCHANT_ID
ARG PHONEPE_CLIENT_SECRET
ARG PHONEPE_CLIENT_VERSION
ARG PHONEPE_ENV
ARG NEXT_PUBLIC_APP_URL

# 2) Export them so Next.js sees them during `npm run build`
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_KEY=$NEXT_PUBLIC_SUPABASE_KEY
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV NEXT_PUBLIC_PHONEPE_CLIENT_ID=$NEXT_PUBLIC_PHONEPE_CLIENT_ID
ENV NEXT_PUBLIC_PHONEPE_MERCHANT_ID=$NEXT_PUBLIC_PHONEPE_MERCHANT_ID
ENV PHONEPE_CLIENT_SECRET=$PHONEPE_CLIENT_SECRET
ENV PHONEPE_CLIENT_VERSION=$PHONEPE_CLIENT_VERSION
ENV PHONEPE_ENV=$PHONEPE_ENV
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Run
FROM node:20-alpine
WORKDIR /app

# 3) Re-declare GEMINI_API_KEY if you need it in server code at runtime
ARG GEMINI_API_KEY
ENV GEMINI_API_KEY=$GEMINI_API_KEY

COPY package*.json ./
RUN npm install --omit=dev

# 4) Bring over your build output
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.* ./

EXPOSE 3000
CMD ["npm", "start"]
