/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/saved_jobs": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.saved_jobs.id"];
          created_at?: parameters["rowFilter.saved_jobs.created_at"];
          record_id?: parameters["rowFilter.saved_jobs.record_id"];
          user_id?: parameters["rowFilter.saved_jobs.user_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["saved_jobs"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** saved_jobs */
          saved_jobs?: definitions["saved_jobs"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.saved_jobs.id"];
          created_at?: parameters["rowFilter.saved_jobs.created_at"];
          record_id?: parameters["rowFilter.saved_jobs.record_id"];
          user_id?: parameters["rowFilter.saved_jobs.user_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.saved_jobs.id"];
          created_at?: parameters["rowFilter.saved_jobs.created_at"];
          record_id?: parameters["rowFilter.saved_jobs.record_id"];
          user_id?: parameters["rowFilter.saved_jobs.user_id"];
        };
        body: {
          /** saved_jobs */
          saved_jobs?: definitions["saved_jobs"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/job_recommendations": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.job_recommendations.id"];
          user_id?: parameters["rowFilter.job_recommendations.user_id"];
          job_id?: parameters["rowFilter.job_recommendations.job_id"];
          job_source?: parameters["rowFilter.job_recommendations.job_source"];
          /** Recommendation score from 0.0 to 1.0, higher is better match */
          score?: parameters["rowFilter.job_recommendations.score"];
          /** Array of strings explaining why this job was recommended */
          reasons?: parameters["rowFilter.job_recommendations.reasons"];
          created_at?: parameters["rowFilter.job_recommendations.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["job_recommendations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** job_recommendations */
          job_recommendations?: definitions["job_recommendations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.job_recommendations.id"];
          user_id?: parameters["rowFilter.job_recommendations.user_id"];
          job_id?: parameters["rowFilter.job_recommendations.job_id"];
          job_source?: parameters["rowFilter.job_recommendations.job_source"];
          /** Recommendation score from 0.0 to 1.0, higher is better match */
          score?: parameters["rowFilter.job_recommendations.score"];
          /** Array of strings explaining why this job was recommended */
          reasons?: parameters["rowFilter.job_recommendations.reasons"];
          created_at?: parameters["rowFilter.job_recommendations.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.job_recommendations.id"];
          user_id?: parameters["rowFilter.job_recommendations.user_id"];
          job_id?: parameters["rowFilter.job_recommendations.job_id"];
          job_source?: parameters["rowFilter.job_recommendations.job_source"];
          /** Recommendation score from 0.0 to 1.0, higher is better match */
          score?: parameters["rowFilter.job_recommendations.score"];
          /** Array of strings explaining why this job was recommended */
          reasons?: parameters["rowFilter.job_recommendations.reasons"];
          created_at?: parameters["rowFilter.job_recommendations.created_at"];
        };
        body: {
          /** job_recommendations */
          job_recommendations?: definitions["job_recommendations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/hot_leads_new_suggestions": {
    get: {
      parameters: {
        query: {
          suggestion?: parameters["rowFilter.hot_leads_new_suggestions.suggestion"];
          source_col?: parameters["rowFilter.hot_leads_new_suggestions.source_col"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["hot_leads_new_suggestions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** hot_leads_new_suggestions */
          hot_leads_new_suggestions?: definitions["hot_leads_new_suggestions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          suggestion?: parameters["rowFilter.hot_leads_new_suggestions.suggestion"];
          source_col?: parameters["rowFilter.hot_leads_new_suggestions.source_col"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          suggestion?: parameters["rowFilter.hot_leads_new_suggestions.suggestion"];
          source_col?: parameters["rowFilter.hot_leads_new_suggestions.source_col"];
        };
        body: {
          /** hot_leads_new_suggestions */
          hot_leads_new_suggestions?: definitions["hot_leads_new_suggestions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/lmia_suggestions": {
    get: {
      parameters: {
        query: {
          suggestion?: parameters["rowFilter.lmia_suggestions.suggestion"];
          source_col?: parameters["rowFilter.lmia_suggestions.source_col"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["lmia_suggestions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** lmia_suggestions */
          lmia_suggestions?: definitions["lmia_suggestions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          suggestion?: parameters["rowFilter.lmia_suggestions.suggestion"];
          source_col?: parameters["rowFilter.lmia_suggestions.source_col"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          suggestion?: parameters["rowFilter.lmia_suggestions.suggestion"];
          source_col?: parameters["rowFilter.lmia_suggestions.source_col"];
        };
        body: {
          /** lmia_suggestions */
          lmia_suggestions?: definitions["lmia_suggestions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/lmia": {
    get: {
      parameters: {
        query: {
          territory?: parameters["rowFilter.lmia.territory"];
          program?: parameters["rowFilter.lmia.program"];
          city?: parameters["rowFilter.lmia.city"];
          postal_code?: parameters["rowFilter.lmia.postal_code"];
          approved_lmias?: parameters["rowFilter.lmia.approved_lmias"];
          approved_positions?: parameters["rowFilter.lmia.approved_positions"];
          lmia_period?: parameters["rowFilter.lmia.lmia_period"];
          lmia_year?: parameters["rowFilter.lmia.lmia_year"];
          phone_1?: parameters["rowFilter.lmia.phone_1"];
          email_1?: parameters["rowFilter.lmia.email_1"];
          priority_occupation?: parameters["rowFilter.lmia.priority_occupation"];
          employer?: parameters["rowFilter.lmia.employer"];
          noc_code?: parameters["rowFilter.lmia.noc_code"];
          job_title?: parameters["rowFilter.lmia.job_title"];
          email?: parameters["rowFilter.lmia.email"];
          phone?: parameters["rowFilter.lmia.phone"];
          RecordID?: parameters["rowFilter.lmia.RecordID"];
          city_norm?: parameters["rowFilter.lmia.city_norm"];
          territory_norm?: parameters["rowFilter.lmia.territory_norm"];
          program_norm?: parameters["rowFilter.lmia.program_norm"];
          postal_code_norm?: parameters["rowFilter.lmia.postal_code_norm"];
          lmia_period_norm?: parameters["rowFilter.lmia.lmia_period_norm"];
          priority_occupation_norm?: parameters["rowFilter.lmia.priority_occupation_norm"];
          employer_norm?: parameters["rowFilter.lmia.employer_norm"];
          noc_code_norm?: parameters["rowFilter.lmia.noc_code_norm"];
          job_title_norm?: parameters["rowFilter.lmia.job_title_norm"];
          tier?: parameters["rowFilter.lmia.tier"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["lmia"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** lmia */
          lmia?: definitions["lmia"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          territory?: parameters["rowFilter.lmia.territory"];
          program?: parameters["rowFilter.lmia.program"];
          city?: parameters["rowFilter.lmia.city"];
          postal_code?: parameters["rowFilter.lmia.postal_code"];
          approved_lmias?: parameters["rowFilter.lmia.approved_lmias"];
          approved_positions?: parameters["rowFilter.lmia.approved_positions"];
          lmia_period?: parameters["rowFilter.lmia.lmia_period"];
          lmia_year?: parameters["rowFilter.lmia.lmia_year"];
          phone_1?: parameters["rowFilter.lmia.phone_1"];
          email_1?: parameters["rowFilter.lmia.email_1"];
          priority_occupation?: parameters["rowFilter.lmia.priority_occupation"];
          employer?: parameters["rowFilter.lmia.employer"];
          noc_code?: parameters["rowFilter.lmia.noc_code"];
          job_title?: parameters["rowFilter.lmia.job_title"];
          email?: parameters["rowFilter.lmia.email"];
          phone?: parameters["rowFilter.lmia.phone"];
          RecordID?: parameters["rowFilter.lmia.RecordID"];
          city_norm?: parameters["rowFilter.lmia.city_norm"];
          territory_norm?: parameters["rowFilter.lmia.territory_norm"];
          program_norm?: parameters["rowFilter.lmia.program_norm"];
          postal_code_norm?: parameters["rowFilter.lmia.postal_code_norm"];
          lmia_period_norm?: parameters["rowFilter.lmia.lmia_period_norm"];
          priority_occupation_norm?: parameters["rowFilter.lmia.priority_occupation_norm"];
          employer_norm?: parameters["rowFilter.lmia.employer_norm"];
          noc_code_norm?: parameters["rowFilter.lmia.noc_code_norm"];
          job_title_norm?: parameters["rowFilter.lmia.job_title_norm"];
          tier?: parameters["rowFilter.lmia.tier"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          territory?: parameters["rowFilter.lmia.territory"];
          program?: parameters["rowFilter.lmia.program"];
          city?: parameters["rowFilter.lmia.city"];
          postal_code?: parameters["rowFilter.lmia.postal_code"];
          approved_lmias?: parameters["rowFilter.lmia.approved_lmias"];
          approved_positions?: parameters["rowFilter.lmia.approved_positions"];
          lmia_period?: parameters["rowFilter.lmia.lmia_period"];
          lmia_year?: parameters["rowFilter.lmia.lmia_year"];
          phone_1?: parameters["rowFilter.lmia.phone_1"];
          email_1?: parameters["rowFilter.lmia.email_1"];
          priority_occupation?: parameters["rowFilter.lmia.priority_occupation"];
          employer?: parameters["rowFilter.lmia.employer"];
          noc_code?: parameters["rowFilter.lmia.noc_code"];
          job_title?: parameters["rowFilter.lmia.job_title"];
          email?: parameters["rowFilter.lmia.email"];
          phone?: parameters["rowFilter.lmia.phone"];
          RecordID?: parameters["rowFilter.lmia.RecordID"];
          city_norm?: parameters["rowFilter.lmia.city_norm"];
          territory_norm?: parameters["rowFilter.lmia.territory_norm"];
          program_norm?: parameters["rowFilter.lmia.program_norm"];
          postal_code_norm?: parameters["rowFilter.lmia.postal_code_norm"];
          lmia_period_norm?: parameters["rowFilter.lmia.lmia_period_norm"];
          priority_occupation_norm?: parameters["rowFilter.lmia.priority_occupation_norm"];
          employer_norm?: parameters["rowFilter.lmia.employer_norm"];
          noc_code_norm?: parameters["rowFilter.lmia.noc_code_norm"];
          job_title_norm?: parameters["rowFilter.lmia.job_title_norm"];
          tier?: parameters["rowFilter.lmia.tier"];
        };
        body: {
          /** lmia */
          lmia?: definitions["lmia"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/credits": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.credits.id"];
          created_at?: parameters["rowFilter.credits.created_at"];
          total_credit?: parameters["rowFilter.credits.total_credit"];
          used_credit?: parameters["rowFilter.credits.used_credit"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["credits"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** credits */
          credits?: definitions["credits"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.credits.id"];
          created_at?: parameters["rowFilter.credits.created_at"];
          total_credit?: parameters["rowFilter.credits.total_credit"];
          used_credit?: parameters["rowFilter.credits.used_credit"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.credits.id"];
          created_at?: parameters["rowFilter.credits.created_at"];
          total_credit?: parameters["rowFilter.credits.total_credit"];
          used_credit?: parameters["rowFilter.credits.used_credit"];
        };
        body: {
          /** credits */
          credits?: definitions["credits"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/transactions": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.transactions.id"];
          user_id?: parameters["rowFilter.transactions.user_id"];
          /** Unique transaction ID generated by our system */
          merchant_transaction_id?: parameters["rowFilter.transactions.merchant_transaction_id"];
          /** Transaction ID returned by PhonePe after payment */
          phonepe_transaction_id?: parameters["rowFilter.transactions.phonepe_transaction_id"];
          /** Payment amount in the specified currency */
          amount?: parameters["rowFilter.transactions.amount"];
          /** Currency code (INR, CAD, etc.) */
          currency?: parameters["rowFilter.transactions.currency"];
          /** Name of the purchased plan */
          plan_name?: parameters["rowFilter.transactions.plan_name"];
          /** Current payment status */
          status?: parameters["rowFilter.transactions.status"];
          /** Payment method used (UPI, Card, etc.) */
          payment_method?: parameters["rowFilter.transactions.payment_method"];
          created_at?: parameters["rowFilter.transactions.created_at"];
          updated_at?: parameters["rowFilter.transactions.updated_at"];
          /** Additional payment metadata and callback responses */
          metadata?: parameters["rowFilter.transactions.metadata"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["transactions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** transactions */
          transactions?: definitions["transactions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.transactions.id"];
          user_id?: parameters["rowFilter.transactions.user_id"];
          /** Unique transaction ID generated by our system */
          merchant_transaction_id?: parameters["rowFilter.transactions.merchant_transaction_id"];
          /** Transaction ID returned by PhonePe after payment */
          phonepe_transaction_id?: parameters["rowFilter.transactions.phonepe_transaction_id"];
          /** Payment amount in the specified currency */
          amount?: parameters["rowFilter.transactions.amount"];
          /** Currency code (INR, CAD, etc.) */
          currency?: parameters["rowFilter.transactions.currency"];
          /** Name of the purchased plan */
          plan_name?: parameters["rowFilter.transactions.plan_name"];
          /** Current payment status */
          status?: parameters["rowFilter.transactions.status"];
          /** Payment method used (UPI, Card, etc.) */
          payment_method?: parameters["rowFilter.transactions.payment_method"];
          created_at?: parameters["rowFilter.transactions.created_at"];
          updated_at?: parameters["rowFilter.transactions.updated_at"];
          /** Additional payment metadata and callback responses */
          metadata?: parameters["rowFilter.transactions.metadata"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.transactions.id"];
          user_id?: parameters["rowFilter.transactions.user_id"];
          /** Unique transaction ID generated by our system */
          merchant_transaction_id?: parameters["rowFilter.transactions.merchant_transaction_id"];
          /** Transaction ID returned by PhonePe after payment */
          phonepe_transaction_id?: parameters["rowFilter.transactions.phonepe_transaction_id"];
          /** Payment amount in the specified currency */
          amount?: parameters["rowFilter.transactions.amount"];
          /** Currency code (INR, CAD, etc.) */
          currency?: parameters["rowFilter.transactions.currency"];
          /** Name of the purchased plan */
          plan_name?: parameters["rowFilter.transactions.plan_name"];
          /** Current payment status */
          status?: parameters["rowFilter.transactions.status"];
          /** Payment method used (UPI, Card, etc.) */
          payment_method?: parameters["rowFilter.transactions.payment_method"];
          created_at?: parameters["rowFilter.transactions.created_at"];
          updated_at?: parameters["rowFilter.transactions.updated_at"];
          /** Additional payment metadata and callback responses */
          metadata?: parameters["rowFilter.transactions.metadata"];
        };
        body: {
          /** transactions */
          transactions?: definitions["transactions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/trending_job": {
    get: {
      parameters: {
        query: {
          date_of_job_posting?: parameters["rowFilter.trending_job.date_of_job_posting"];
          state?: parameters["rowFilter.trending_job.state"];
          city?: parameters["rowFilter.trending_job.city"];
          email?: parameters["rowFilter.trending_job.email"];
          phone?: parameters["rowFilter.trending_job.phone"];
          category?: parameters["rowFilter.trending_job.category"];
          job_title?: parameters["rowFilter.trending_job.job_title"];
          noc_code?: parameters["rowFilter.trending_job.noc_code"];
          employer?: parameters["rowFilter.trending_job.employer"];
          id?: parameters["rowFilter.trending_job.id"];
          state_norm?: parameters["rowFilter.trending_job.state_norm"];
          city_norm?: parameters["rowFilter.trending_job.city_norm"];
          category_norm?: parameters["rowFilter.trending_job.category_norm"];
          job_title_norm?: parameters["rowFilter.trending_job.job_title_norm"];
          noc_code_norm?: parameters["rowFilter.trending_job.noc_code_norm"];
          employer_norm?: parameters["rowFilter.trending_job.employer_norm"];
          job_description?: parameters["rowFilter.trending_job.job_description"];
          lat?: parameters["rowFilter.trending_job.lat"];
          lng?: parameters["rowFilter.trending_job.lng"];
          salary?: parameters["rowFilter.trending_job.salary"];
          positions?: parameters["rowFilter.trending_job.positions"];
          year?: parameters["rowFilter.trending_job.year"];
          tier?: parameters["rowFilter.trending_job.tier"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["trending_job"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** trending_job */
          trending_job?: definitions["trending_job"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          date_of_job_posting?: parameters["rowFilter.trending_job.date_of_job_posting"];
          state?: parameters["rowFilter.trending_job.state"];
          city?: parameters["rowFilter.trending_job.city"];
          email?: parameters["rowFilter.trending_job.email"];
          phone?: parameters["rowFilter.trending_job.phone"];
          category?: parameters["rowFilter.trending_job.category"];
          job_title?: parameters["rowFilter.trending_job.job_title"];
          noc_code?: parameters["rowFilter.trending_job.noc_code"];
          employer?: parameters["rowFilter.trending_job.employer"];
          id?: parameters["rowFilter.trending_job.id"];
          state_norm?: parameters["rowFilter.trending_job.state_norm"];
          city_norm?: parameters["rowFilter.trending_job.city_norm"];
          category_norm?: parameters["rowFilter.trending_job.category_norm"];
          job_title_norm?: parameters["rowFilter.trending_job.job_title_norm"];
          noc_code_norm?: parameters["rowFilter.trending_job.noc_code_norm"];
          employer_norm?: parameters["rowFilter.trending_job.employer_norm"];
          job_description?: parameters["rowFilter.trending_job.job_description"];
          lat?: parameters["rowFilter.trending_job.lat"];
          lng?: parameters["rowFilter.trending_job.lng"];
          salary?: parameters["rowFilter.trending_job.salary"];
          positions?: parameters["rowFilter.trending_job.positions"];
          year?: parameters["rowFilter.trending_job.year"];
          tier?: parameters["rowFilter.trending_job.tier"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          date_of_job_posting?: parameters["rowFilter.trending_job.date_of_job_posting"];
          state?: parameters["rowFilter.trending_job.state"];
          city?: parameters["rowFilter.trending_job.city"];
          email?: parameters["rowFilter.trending_job.email"];
          phone?: parameters["rowFilter.trending_job.phone"];
          category?: parameters["rowFilter.trending_job.category"];
          job_title?: parameters["rowFilter.trending_job.job_title"];
          noc_code?: parameters["rowFilter.trending_job.noc_code"];
          employer?: parameters["rowFilter.trending_job.employer"];
          id?: parameters["rowFilter.trending_job.id"];
          state_norm?: parameters["rowFilter.trending_job.state_norm"];
          city_norm?: parameters["rowFilter.trending_job.city_norm"];
          category_norm?: parameters["rowFilter.trending_job.category_norm"];
          job_title_norm?: parameters["rowFilter.trending_job.job_title_norm"];
          noc_code_norm?: parameters["rowFilter.trending_job.noc_code_norm"];
          employer_norm?: parameters["rowFilter.trending_job.employer_norm"];
          job_description?: parameters["rowFilter.trending_job.job_description"];
          lat?: parameters["rowFilter.trending_job.lat"];
          lng?: parameters["rowFilter.trending_job.lng"];
          salary?: parameters["rowFilter.trending_job.salary"];
          positions?: parameters["rowFilter.trending_job.positions"];
          year?: parameters["rowFilter.trending_job.year"];
          tier?: parameters["rowFilter.trending_job.tier"];
        };
        body: {
          /** trending_job */
          trending_job?: definitions["trending_job"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/noc_tier": {
    get: {
      parameters: {
        query: {
          noc_code?: parameters["rowFilter.noc_tier.noc_code"];
          Title?: parameters["rowFilter.noc_tier.Title"];
          tier?: parameters["rowFilter.noc_tier.tier"];
          Category?: parameters["rowFilter.noc_tier.Category"];
          id?: parameters["rowFilter.noc_tier.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["noc_tier"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** noc_tier */
          noc_tier?: definitions["noc_tier"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          noc_code?: parameters["rowFilter.noc_tier.noc_code"];
          Title?: parameters["rowFilter.noc_tier.Title"];
          tier?: parameters["rowFilter.noc_tier.tier"];
          Category?: parameters["rowFilter.noc_tier.Category"];
          id?: parameters["rowFilter.noc_tier.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          noc_code?: parameters["rowFilter.noc_tier.noc_code"];
          Title?: parameters["rowFilter.noc_tier.Title"];
          tier?: parameters["rowFilter.noc_tier.tier"];
          Category?: parameters["rowFilter.noc_tier.Category"];
          id?: parameters["rowFilter.noc_tier.id"];
        };
        body: {
          /** noc_tier */
          noc_tier?: definitions["noc_tier"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/searches": {
    get: {
      parameters: {
        query: {
          keyword?: parameters["rowFilter.searches.keyword"];
          save?: parameters["rowFilter.searches.save"];
          id?: parameters["rowFilter.searches.id"];
          search_id?: parameters["rowFilter.searches.search_id"];
          created_at?: parameters["rowFilter.searches.created_at"];
          /** JSONB object storing applied filters: {location, salary_min, salary_max, noc_code, etc.} */
          filters?: parameters["rowFilter.searches.filters"];
          /** Number of results returned for this search */
          results_count?: parameters["rowFilter.searches.results_count"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["searches"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** searches */
          searches?: definitions["searches"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          keyword?: parameters["rowFilter.searches.keyword"];
          save?: parameters["rowFilter.searches.save"];
          id?: parameters["rowFilter.searches.id"];
          search_id?: parameters["rowFilter.searches.search_id"];
          created_at?: parameters["rowFilter.searches.created_at"];
          /** JSONB object storing applied filters: {location, salary_min, salary_max, noc_code, etc.} */
          filters?: parameters["rowFilter.searches.filters"];
          /** Number of results returned for this search */
          results_count?: parameters["rowFilter.searches.results_count"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          keyword?: parameters["rowFilter.searches.keyword"];
          save?: parameters["rowFilter.searches.save"];
          id?: parameters["rowFilter.searches.id"];
          search_id?: parameters["rowFilter.searches.search_id"];
          created_at?: parameters["rowFilter.searches.created_at"];
          /** JSONB object storing applied filters: {location, salary_min, salary_max, noc_code, etc.} */
          filters?: parameters["rowFilter.searches.filters"];
          /** Number of results returned for this search */
          results_count?: parameters["rowFilter.searches.results_count"];
        };
        body: {
          /** searches */
          searches?: definitions["searches"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/visitors": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.visitors.id"];
          ip_address?: parameters["rowFilter.visitors.ip_address"];
          location?: parameters["rowFilter.visitors.location"];
          first_visit?: parameters["rowFilter.visitors.first_visit"];
          created_at?: parameters["rowFilter.visitors.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["visitors"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** visitors */
          visitors?: definitions["visitors"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.visitors.id"];
          ip_address?: parameters["rowFilter.visitors.ip_address"];
          location?: parameters["rowFilter.visitors.location"];
          first_visit?: parameters["rowFilter.visitors.first_visit"];
          created_at?: parameters["rowFilter.visitors.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.visitors.id"];
          ip_address?: parameters["rowFilter.visitors.ip_address"];
          location?: parameters["rowFilter.visitors.location"];
          first_visit?: parameters["rowFilter.visitors.first_visit"];
          created_at?: parameters["rowFilter.visitors.created_at"];
        };
        body: {
          /** visitors */
          visitors?: definitions["visitors"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/category": {
    get: {
      parameters: {
        query: {
          noc_code?: parameters["rowFilter.category.noc_code"];
          occupation?: parameters["rowFilter.category.occupation"];
          category?: parameters["rowFilter.category.category"];
          id?: parameters["rowFilter.category.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["category"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** category */
          category?: definitions["category"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          noc_code?: parameters["rowFilter.category.noc_code"];
          occupation?: parameters["rowFilter.category.occupation"];
          category?: parameters["rowFilter.category.category"];
          id?: parameters["rowFilter.category.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          noc_code?: parameters["rowFilter.category.noc_code"];
          occupation?: parameters["rowFilter.category.occupation"];
          category?: parameters["rowFilter.category.category"];
          id?: parameters["rowFilter.category.id"];
        };
        body: {
          /** category */
          category?: definitions["category"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/user_preferences": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user_preferences.id"];
          user_id?: parameters["rowFilter.user_preferences.user_id"];
          preferred_job_titles?: parameters["rowFilter.user_preferences.preferred_job_titles"];
          preferred_locations?: parameters["rowFilter.user_preferences.preferred_locations"];
          preferred_industries?: parameters["rowFilter.user_preferences.preferred_industries"];
          salary_min?: parameters["rowFilter.user_preferences.salary_min"];
          salary_max?: parameters["rowFilter.user_preferences.salary_max"];
          work_authorization?: parameters["rowFilter.user_preferences.work_authorization"];
          remote_preference?: parameters["rowFilter.user_preferences.remote_preference"];
          experience_level?: parameters["rowFilter.user_preferences.experience_level"];
          company_size_preference?: parameters["rowFilter.user_preferences.company_size_preference"];
          created_at?: parameters["rowFilter.user_preferences.created_at"];
          updated_at?: parameters["rowFilter.user_preferences.updated_at"];
          preferred_noc_codes?: parameters["rowFilter.user_preferences.preferred_noc_codes"];
          preferred_company_tiers?: parameters["rowFilter.user_preferences.preferred_company_tiers"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["user_preferences"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** user_preferences */
          user_preferences?: definitions["user_preferences"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user_preferences.id"];
          user_id?: parameters["rowFilter.user_preferences.user_id"];
          preferred_job_titles?: parameters["rowFilter.user_preferences.preferred_job_titles"];
          preferred_locations?: parameters["rowFilter.user_preferences.preferred_locations"];
          preferred_industries?: parameters["rowFilter.user_preferences.preferred_industries"];
          salary_min?: parameters["rowFilter.user_preferences.salary_min"];
          salary_max?: parameters["rowFilter.user_preferences.salary_max"];
          work_authorization?: parameters["rowFilter.user_preferences.work_authorization"];
          remote_preference?: parameters["rowFilter.user_preferences.remote_preference"];
          experience_level?: parameters["rowFilter.user_preferences.experience_level"];
          company_size_preference?: parameters["rowFilter.user_preferences.company_size_preference"];
          created_at?: parameters["rowFilter.user_preferences.created_at"];
          updated_at?: parameters["rowFilter.user_preferences.updated_at"];
          preferred_noc_codes?: parameters["rowFilter.user_preferences.preferred_noc_codes"];
          preferred_company_tiers?: parameters["rowFilter.user_preferences.preferred_company_tiers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user_preferences.id"];
          user_id?: parameters["rowFilter.user_preferences.user_id"];
          preferred_job_titles?: parameters["rowFilter.user_preferences.preferred_job_titles"];
          preferred_locations?: parameters["rowFilter.user_preferences.preferred_locations"];
          preferred_industries?: parameters["rowFilter.user_preferences.preferred_industries"];
          salary_min?: parameters["rowFilter.user_preferences.salary_min"];
          salary_max?: parameters["rowFilter.user_preferences.salary_max"];
          work_authorization?: parameters["rowFilter.user_preferences.work_authorization"];
          remote_preference?: parameters["rowFilter.user_preferences.remote_preference"];
          experience_level?: parameters["rowFilter.user_preferences.experience_level"];
          company_size_preference?: parameters["rowFilter.user_preferences.company_size_preference"];
          created_at?: parameters["rowFilter.user_preferences.created_at"];
          updated_at?: parameters["rowFilter.user_preferences.updated_at"];
          preferred_noc_codes?: parameters["rowFilter.user_preferences.preferred_noc_codes"];
          preferred_company_tiers?: parameters["rowFilter.user_preferences.preferred_company_tiers"];
        };
        body: {
          /** user_preferences */
          user_preferences?: definitions["user_preferences"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/schema_migrations": {
    get: {
      parameters: {
        query: {
          filename?: parameters["rowFilter.schema_migrations.filename"];
          applied_at?: parameters["rowFilter.schema_migrations.applied_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["schema_migrations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** schema_migrations */
          schema_migrations?: definitions["schema_migrations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          filename?: parameters["rowFilter.schema_migrations.filename"];
          applied_at?: parameters["rowFilter.schema_migrations.applied_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          filename?: parameters["rowFilter.schema_migrations.filename"];
          applied_at?: parameters["rowFilter.schema_migrations.applied_at"];
        };
        body: {
          /** schema_migrations */
          schema_migrations?: definitions["schema_migrations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/cleanup_tredning_job_exact_duplicates": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/rpc_search_hot_leads": {
    get: {
      parameters: {
        query: {
          term: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            term: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/get_distinct_values_with_count": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            column_name: string;
            /** Format: text */
            table_name: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/get_cities_by_province": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            p_province: string;
            /** Format: text */
            p_search?: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/rpc_suggest_lmia": {
    get: {
      parameters: {
        query: {
          term: string;
          p_limit?: number;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: {
            /** Format: integer */
            p_limit?: number;
            /** Format: text */
            term: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/show_trgm": {
    get: {
      parameters: {};
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            "": string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/check_filter_availability": {
    get: {
      parameters: {
        query: {
          p_table: string;
          p_column: string;
          p_filters?: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            p_column: string;
            /** Format: jsonb */
            p_filters?: unknown;
            /** Format: text */
            p_table: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/clean_old_recommendations": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/get_companies_by_tier": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: boolean */
            p_is_lmia: boolean;
            /** Format: integer */
            p_limit?: number;
            /** Format: integer */
            p_tier: number;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/dynamic_analytics": {
    get: {
      parameters: {
        query: {
          table_name: string;
          filters_json: string;
          group_cols: string;
          measure_expr: string;
          date_column?: string;
          years_back?: number;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            date_column?: string;
            /** Format: jsonb */
            filters_json: unknown;
            /** Format: text[] */
            group_cols: string[];
            /** Format: text */
            measure_expr: string;
            /** Format: text */
            table_name: string;
            /** Format: integer */
            years_back?: number;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/suggest_trending_job": {
    get: {
      parameters: {
        query: {
          p_field: string;
          p_q: string;
          p_limit?: number;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            p_field: string;
            /** Format: integer */
            p_limit?: number;
            /** Format: text */
            p_q: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/rpc_search_lmia": {
    get: {
      parameters: {
        query: {
          term: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            term: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/suggest_location": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: integer */
            p_limit?: number;
            /** Format: text */
            p_q: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/rpc_suggest_hot_leads_new": {
    get: {
      parameters: {
        query: {
          term: string;
          p_limit?: number;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: {
            /** Format: integer */
            p_limit?: number;
            /** Format: text */
            term: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/get_facet_counts_with_filters": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            p_column_name: string;
            /** Format: jsonb */
            p_filters?: unknown;
            /** Format: text */
            p_search_field?: string;
            /** Format: text */
            p_search_term?: string;
            /** Format: text */
            p_table_name: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/suggest_lmia": {
    get: {
      parameters: {
        query: {
          p_field: string;
          p_q: string;
          p_limit?: number;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            p_field: string;
            /** Format: integer */
            p_limit?: number;
            /** Format: text */
            p_q: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/show_limit": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/cleanup_trending_job_exact_duplicates": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/get_wage_stats": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            p_noc_code: string;
            /** Format: text */
            p_province?: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/get_provinces": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/get_dashboard_data": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text[] */
            filter_cols: string[];
            /** Format: text[] */
            filter_vals: string[];
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  saved_jobs: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /** Format: text */
    record_id?: string;
    /** Format: uuid */
    user_id?: string;
  };
  /** @description Stores cached job recommendations with scores and reasons */
  job_recommendations: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: uuid */
    user_id?: string;
    /** Format: text */
    job_id: string;
    /** Format: text */
    job_source: string;
    /**
     * Format: double precision
     * @description Recommendation score from 0.0 to 1.0, higher is better match
     */
    score: number;
    /**
     * Format: text[]
     * @description Array of strings explaining why this job was recommended
     */
    reasons?: string[];
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
  hot_leads_new_suggestions: {
    /** Format: text */
    suggestion: string;
    /** Format: text */
    source_col: string;
  };
  lmia_suggestions: {
    /** Format: text */
    suggestion: string;
    /** Format: text */
    source_col: string;
  };
  lmia: {
    /** Format: text */
    territory?: string;
    /** Format: text */
    program?: string;
    /** Format: text */
    city?: string;
    /** Format: text */
    postal_code?: string;
    /** Format: text */
    approved_lmias?: string;
    /** Format: text */
    approved_positions?: string;
    /** Format: text */
    lmia_period?: string;
    /** Format: text */
    lmia_year?: string;
    /** Format: text */
    phone_1?: string;
    /** Format: text */
    email_1?: string;
    /** Format: text */
    priority_occupation?: string;
    /** Format: text */
    employer?: string;
    /** Format: text */
    noc_code?: string;
    /** Format: text */
    job_title?: string;
    /** Format: text */
    email?: string;
    /** Format: text */
    phone?: string;
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    RecordID: string;
    /** Format: text */
    city_norm?: string;
    /** Format: text */
    territory_norm?: string;
    /** Format: text */
    program_norm?: string;
    /** Format: text */
    postal_code_norm?: string;
    /** Format: text */
    lmia_period_norm?: string;
    /** Format: text */
    priority_occupation_norm?: string;
    /** Format: text */
    employer_norm?: string;
    /** Format: text */
    noc_code_norm?: string;
    /** Format: text */
    job_title_norm?: string;
    /** Format: text */
    tier?: string;
  };
  credits: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: bigint */
    total_credit?: number;
    /** Format: bigint */
    used_credit?: number;
  };
  /** @description Stores payment transaction records from PhonePe gateway */
  transactions: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: uuid */
    user_id: string;
    /**
     * Format: character varying
     * @description Unique transaction ID generated by our system
     */
    merchant_transaction_id: string;
    /**
     * Format: character varying
     * @description Transaction ID returned by PhonePe after payment
     */
    phonepe_transaction_id?: string;
    /**
     * Format: numeric
     * @description Payment amount in the specified currency
     */
    amount: number;
    /**
     * Format: character varying
     * @description Currency code (INR, CAD, etc.)
     * @default INR
     */
    currency: string;
    /**
     * Format: character varying
     * @description Name of the purchased plan
     */
    plan_name: string;
    /**
     * Format: character varying
     * @description Current payment status
     * @default PENDING
     */
    status: string;
    /**
     * Format: character varying
     * @description Payment method used (UPI, Card, etc.)
     */
    payment_method?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at?: string;
    /**
     * Format: jsonb
     * @description Additional payment metadata and callback responses
     */
    metadata?: unknown;
  };
  trending_job: {
    /** Format: date */
    date_of_job_posting?: string;
    /** Format: text */
    state?: string;
    /** Format: text */
    city?: string;
    /** Format: text */
    email?: string;
    /** Format: text */
    phone?: string;
    /** Format: text */
    category?: string;
    /** Format: text */
    job_title?: string;
    /** Format: text */
    noc_code?: string;
    /** Format: text */
    employer?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    state_norm?: string;
    /** Format: text */
    city_norm?: string;
    /** Format: text */
    category_norm?: string;
    /** Format: text */
    job_title_norm?: string;
    /** Format: text */
    noc_code_norm?: string;
    /** Format: text */
    employer_norm?: string;
    /** Format: jsonb */
    job_description?: unknown;
    /** Format: double precision */
    lat?: number;
    /** Format: double precision */
    lng?: number;
    /** Format: text */
    salary?: string;
    /** Format: smallint */
    positions?: number;
    /** Format: text */
    year?: string;
    /** Format: text */
    tier?: string;
  };
  noc_tier: {
    /** Format: text */
    noc_code?: string;
    /** Format: text */
    Title?: string;
    /** Format: text */
    tier?: string;
    /** Format: text */
    Category?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
  };
  searches: {
    /** Format: text */
    keyword?: string;
    /** Format: boolean */
    save?: boolean;
    /** Format: uuid */
    id?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    search_id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: jsonb
     * @description JSONB object storing applied filters: {location, salary_min, salary_max, noc_code, etc.}
     */
    filters?: unknown;
    /**
     * Format: integer
     * @description Number of results returned for this search
     */
    results_count?: number;
  };
  visitors: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: text */
    ip_address: string;
    /** Format: jsonb */
    location?: unknown;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    first_visit?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
  category: {
    /** Format: text */
    noc_code?: string;
    /** Format: text */
    occupation?: string;
    /** Format: text */
    category?: string;
    /**
     * Format: smallint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
  };
  user_preferences: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: uuid */
    user_id?: string;
    /** Format: text[] */
    preferred_job_titles?: string[];
    /** Format: text[] */
    preferred_locations?: string[];
    /** Format: text[] */
    preferred_industries?: string[];
    /** Format: integer */
    salary_min?: number;
    /** Format: integer */
    salary_max?: number;
    /** Format: text */
    work_authorization?: string;
    /**
     * Format: text
     * @default any
     */
    remote_preference?: string;
    /** Format: text */
    experience_level?: string;
    /** Format: text[] */
    company_size_preference?: string[];
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at?: string;
    /** Format: text[] */
    preferred_noc_codes?: string[];
    /** Format: text[] */
    preferred_company_tiers?: string[];
  };
  schema_migrations: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    filename: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    applied_at: string;
  };
}

export interface parameters {
  /** @description Preference */
  preferParams: string;
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferPost:
  | "return=representation"
  | "return=minimal"
  | "return=none"
  | "resolution=ignore-duplicates"
  | "resolution=merge-duplicates";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description saved_jobs */
  "body.saved_jobs": definitions["saved_jobs"];
  "rowFilter.saved_jobs.id": string;
  "rowFilter.saved_jobs.created_at": string;
  "rowFilter.saved_jobs.record_id": string;
  "rowFilter.saved_jobs.user_id": string;
  /** @description job_recommendations */
  "body.job_recommendations": definitions["job_recommendations"];
  "rowFilter.job_recommendations.id": string;
  "rowFilter.job_recommendations.user_id": string;
  "rowFilter.job_recommendations.job_id": string;
  "rowFilter.job_recommendations.job_source": string;
  /** @description Recommendation score from 0.0 to 1.0, higher is better match */
  "rowFilter.job_recommendations.score": string;
  /** @description Array of strings explaining why this job was recommended */
  "rowFilter.job_recommendations.reasons": string;
  "rowFilter.job_recommendations.created_at": string;
  /** @description hot_leads_new_suggestions */
  "body.hot_leads_new_suggestions": definitions["hot_leads_new_suggestions"];
  "rowFilter.hot_leads_new_suggestions.suggestion": string;
  "rowFilter.hot_leads_new_suggestions.source_col": string;
  /** @description lmia_suggestions */
  "body.lmia_suggestions": definitions["lmia_suggestions"];
  "rowFilter.lmia_suggestions.suggestion": string;
  "rowFilter.lmia_suggestions.source_col": string;
  /** @description lmia */
  "body.lmia": definitions["lmia"];
  "rowFilter.lmia.territory": string;
  "rowFilter.lmia.program": string;
  "rowFilter.lmia.city": string;
  "rowFilter.lmia.postal_code": string;
  "rowFilter.lmia.approved_lmias": string;
  "rowFilter.lmia.approved_positions": string;
  "rowFilter.lmia.lmia_period": string;
  "rowFilter.lmia.lmia_year": string;
  "rowFilter.lmia.phone_1": string;
  "rowFilter.lmia.email_1": string;
  "rowFilter.lmia.priority_occupation": string;
  "rowFilter.lmia.employer": string;
  "rowFilter.lmia.noc_code": string;
  "rowFilter.lmia.job_title": string;
  "rowFilter.lmia.email": string;
  "rowFilter.lmia.phone": string;
  "rowFilter.lmia.RecordID": string;
  "rowFilter.lmia.city_norm": string;
  "rowFilter.lmia.territory_norm": string;
  "rowFilter.lmia.program_norm": string;
  "rowFilter.lmia.postal_code_norm": string;
  "rowFilter.lmia.lmia_period_norm": string;
  "rowFilter.lmia.priority_occupation_norm": string;
  "rowFilter.lmia.employer_norm": string;
  "rowFilter.lmia.noc_code_norm": string;
  "rowFilter.lmia.job_title_norm": string;
  "rowFilter.lmia.tier": string;
  /** @description credits */
  "body.credits": definitions["credits"];
  "rowFilter.credits.id": string;
  "rowFilter.credits.created_at": string;
  "rowFilter.credits.total_credit": string;
  "rowFilter.credits.used_credit": string;
  /** @description transactions */
  "body.transactions": definitions["transactions"];
  "rowFilter.transactions.id": string;
  "rowFilter.transactions.user_id": string;
  /** @description Unique transaction ID generated by our system */
  "rowFilter.transactions.merchant_transaction_id": string;
  /** @description Transaction ID returned by PhonePe after payment */
  "rowFilter.transactions.phonepe_transaction_id": string;
  /** @description Payment amount in the specified currency */
  "rowFilter.transactions.amount": string;
  /** @description Currency code (INR, CAD, etc.) */
  "rowFilter.transactions.currency": string;
  /** @description Name of the purchased plan */
  "rowFilter.transactions.plan_name": string;
  /** @description Current payment status */
  "rowFilter.transactions.status": string;
  /** @description Payment method used (UPI, Card, etc.) */
  "rowFilter.transactions.payment_method": string;
  "rowFilter.transactions.created_at": string;
  "rowFilter.transactions.updated_at": string;
  /** @description Additional payment metadata and callback responses */
  "rowFilter.transactions.metadata": string;
  /** @description trending_job */
  "body.trending_job": definitions["trending_job"];
  "rowFilter.trending_job.date_of_job_posting": string;
  "rowFilter.trending_job.state": string;
  "rowFilter.trending_job.city": string;
  "rowFilter.trending_job.email": string;
  "rowFilter.trending_job.phone": string;
  "rowFilter.trending_job.category": string;
  "rowFilter.trending_job.job_title": string;
  "rowFilter.trending_job.noc_code": string;
  "rowFilter.trending_job.employer": string;
  "rowFilter.trending_job.id": string;
  "rowFilter.trending_job.state_norm": string;
  "rowFilter.trending_job.city_norm": string;
  "rowFilter.trending_job.category_norm": string;
  "rowFilter.trending_job.job_title_norm": string;
  "rowFilter.trending_job.noc_code_norm": string;
  "rowFilter.trending_job.employer_norm": string;
  "rowFilter.trending_job.job_description": string;
  "rowFilter.trending_job.lat": string;
  "rowFilter.trending_job.lng": string;
  "rowFilter.trending_job.salary": string;
  "rowFilter.trending_job.positions": string;
  "rowFilter.trending_job.year": string;
  "rowFilter.trending_job.tier": string;
  /** @description noc_tier */
  "body.noc_tier": definitions["noc_tier"];
  "rowFilter.noc_tier.noc_code": string;
  "rowFilter.noc_tier.Title": string;
  "rowFilter.noc_tier.tier": string;
  "rowFilter.noc_tier.Category": string;
  "rowFilter.noc_tier.id": string;
  /** @description searches */
  "body.searches": definitions["searches"];
  "rowFilter.searches.keyword": string;
  "rowFilter.searches.save": string;
  "rowFilter.searches.id": string;
  "rowFilter.searches.search_id": string;
  "rowFilter.searches.created_at": string;
  /** @description JSONB object storing applied filters: {location, salary_min, salary_max, noc_code, etc.} */
  "rowFilter.searches.filters": string;
  /** @description Number of results returned for this search */
  "rowFilter.searches.results_count": string;
  /** @description visitors */
  "body.visitors": definitions["visitors"];
  "rowFilter.visitors.id": string;
  "rowFilter.visitors.ip_address": string;
  "rowFilter.visitors.location": string;
  "rowFilter.visitors.first_visit": string;
  "rowFilter.visitors.created_at": string;
  /** @description category */
  "body.category": definitions["category"];
  "rowFilter.category.noc_code": string;
  "rowFilter.category.occupation": string;
  "rowFilter.category.category": string;
  "rowFilter.category.id": string;
  /** @description user_preferences */
  "body.user_preferences": definitions["user_preferences"];
  "rowFilter.user_preferences.id": string;
  "rowFilter.user_preferences.user_id": string;
  "rowFilter.user_preferences.preferred_job_titles": string;
  "rowFilter.user_preferences.preferred_locations": string;
  "rowFilter.user_preferences.preferred_industries": string;
  "rowFilter.user_preferences.salary_min": string;
  "rowFilter.user_preferences.salary_max": string;
  "rowFilter.user_preferences.work_authorization": string;
  "rowFilter.user_preferences.remote_preference": string;
  "rowFilter.user_preferences.experience_level": string;
  "rowFilter.user_preferences.company_size_preference": string;
  "rowFilter.user_preferences.created_at": string;
  "rowFilter.user_preferences.updated_at": string;
  "rowFilter.user_preferences.preferred_noc_codes": string;
  "rowFilter.user_preferences.preferred_company_tiers": string;
  /** @description schema_migrations */
  "body.schema_migrations": definitions["schema_migrations"];
  "rowFilter.schema_migrations.filename": string;
  "rowFilter.schema_migrations.applied_at": string;
}

export interface operations { }

export interface external { }

export interface Database {
  public: {
    Tables: {
      [TableName in keyof definitions]: {
        Row: definitions[TableName];
        Insert: Partial<definitions[TableName]>;
        Update: Partial<definitions[TableName]>;
      }
    } & {
      [UnknownTable: string]: {
        Row: Record<string, any>;
        Insert: Record<string, any>;
        Update: Record<string, any>;
      }
    };
    Functions: Record<string, any>;
  }
}
