import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "@/hooks/use-session";
import ReactQueryProvider from "./react-query-provider";
import { SheetProvider } from "@/context/sheet-context";

const monaSans = Mona_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monaSans.variable} antialiased`}>
        <SessionProvider>
          <ReactQueryProvider>
            <SheetProvider>
              {children}
              <Toaster />
            </SheetProvider>
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
