-- Add career_roadmap column to user_profiles to store personalized AI strategy steps
ALTER TABLE public.user_profiles 
ADD COLUMN IF NOT EXISTS career_roadmap JSONB DEFAULT '[]'::jsonb;

-- Comment for clarity
COMMENT ON COLUMN public.user_profiles.career_roadmap IS 'Stores the 7-step Strategic Career Roadmap generated by AI for the candidate';
